### ISSUE TITLE
java.lang.NoClassDefFoundError: org/scalatest/funspec/AnyFunSpecLike

### ISSUE THREAD

**Issue by thymepuns** [scalameta/metals#7916]
### Describe the bug

Afraid I'm not sure how to reproduce this in particular. Was working on 1.6.2 but broken in 1.6.3, working again when rolling back to 1.6.2.

I am not able to run tests in my project (the button to run doesn't appear)

It seems from:
```
Exception in thread "pool-1-thread-806" java.lang.NoClassDefFoundError: org/scalatest/funspec/AnyFunSpecLike
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:962)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:132)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:426)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:339)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	at scala.meta.internal.mtags.OpenClassLoader.$anonfun$loadClassSafe$1(OpenClassLoader.scala:51)
	at scala.util.Try$.apply(Try.scala:217)
	at scala.meta.internal.mtags.OpenClassLoader.loadClassSafe(OpenClassLoader.scala:51)
	at scala.meta.internal.mtags.SymbolIndexBucket.modulePaths(SymbolIndexBucket.scala:366)
	at scala.meta.internal.mtags.SymbolIndexBucket.$anonfun$query0$2(SymbolIndexBucket.scala:221)
	at scala.Option.orElse(Option.scala:477)
	at scala.meta.internal.mtags.SymbolIndexBucket.query0(SymbolIndexBucket.scala:221)
	at scala.meta.internal.mtags.SymbolIndexBucket.query(SymbolIndexBucket.scala:191)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$findSymbolDefinition$1(OnDemandSymbolIndex.scala:143)
	at scala.collection.immutable.List.flatMap(List.scala:283)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.findSymbolDefinition(OnDemandSymbolIndex.scala:143)
	at scala.meta.internal.mtags.OnDemandSymbolIndex.definition(OnDemandSymbolIndex.scala:48)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.applyOrElse(ScalatestTestFinder.scala:67)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.applyOrElse(ScalatestTestFinder.scala:64)
	at scala.collection.immutable.LazyList$.$anonfun$collectImpl$1(LazyList.scala:1098)
	at scala.collection.immutable.LazyList.initState(LazyList.scala:318)
	at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$evaluated(LazyList.scala:331)
	at scala.collection.immutable.LazyList.find(LazyList.scala:339)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.$anonfun$inferScalatestStyle$1(ScalatestTestFinder.scala:79)
	at scala.Option.orElse(Option.scala:477)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.scala$meta$internal$metals$testProvider$frameworks$ScalatestTestFinder$$inferScalatestStyle(ScalatestTestFinder.scala:79)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.$anonfun$applyOrElse$3(ScalatestTestFinder.scala:71)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.$anonfun$applyOrElse$2(ScalatestTestFinder.scala:68)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.applyOrElse(ScalatestTestFinder.scala:67)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.applyOrElse(ScalatestTestFinder.scala:64)
	at scala.collection.immutable.LazyList$.$anonfun$collectImpl$1(LazyList.scala:1098)
	at scala.collection.immutable.LazyList.initState(LazyList.scala:318)
	at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$evaluated(LazyList.scala:331)
	at scala.collection.immutable.LazyList.find(LazyList.scala:339)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.$anonfun$inferScalatestStyle$1(ScalatestTestFinder.scala:79)
	at scala.Option.orElse(Option.scala:477)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.scala$meta$internal$metals$testProvider$frameworks$ScalatestTestFinder$$inferScalatestStyle(ScalatestTestFinder.scala:79)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.$anonfun$applyOrElse$3(ScalatestTestFinder.scala:71)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.$anonfun$applyOrElse$2(ScalatestTestFinder.scala:68)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.applyOrElse(ScalatestTestFinder.scala:67)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder$$anonfun$lazySearch$1$1.applyOrElse(ScalatestTestFinder.scala:64)
	at scala.collection.immutable.LazyList$.$anonfun$collectImpl$1(LazyList.scala:1098)
	at scala.collection.immutable.LazyList.initState(LazyList.scala:318)
	at scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$evaluated(LazyList.scala:331)
	at scala.collection.immutable.LazyList.find(LazyList.scala:339)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.$anonfun$inferScalatestStyle$1(ScalatestTestFinder.scala:79)
	at scala.Option.orElse(Option.scala:477)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.scala$meta$internal$metals$testProvider$frameworks$ScalatestTestFinder$$inferScalatestStyle(ScalatestTestFinder.scala:79)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.$anonfun$findTests$1(ScalatestTestFinder.scala:39)
	at scala.Option.flatMap(Option.scala:283)
	at scala.meta.internal.metals.testProvider.frameworks.ScalatestTestFinder.findTests(ScalatestTestFinder.scala:38)
	at scala.meta.internal.metals.testProvider.TestSuitesProvider.$anonfun$getTestCasesForSuites$3(TestSuitesProvider.scala:330)
	at scala.collection.immutable.List.flatMap(List.scala:283)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at scala.meta.internal.metals.testProvider.TestSuitesProvider.$anonfun$getTestCasesForSuites$2(TestSuitesProvider.scala:310)
	at scala.Option.map(Option.scala:242)
	at scala.meta.internal.metals.testProvider.TestSuitesProvider.getTestCasesForSuites(TestSuitesProvider.scala:309)
	at scala.meta.internal.metals.testProvider.TestSuitesProvider.$anonfun$getTestCasesForPath$1(TestSuitesProvider.scala:284)
	at scala.collection.immutable.List.map(List.scala:236)
	at scala.meta.internal.metals.testProvider.TestSuitesProvider.getTestCasesForPath(TestSuitesProvider.scala:278)
	at scala.meta.internal.metals.testProvider.TestSuitesProvider.$anonfun$didOpen$1(TestSuitesProvider.scala:173)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:691)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: java.lang.ClassNotFoundException: org.scalatest.funspec.AnyFunSpecLike
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:349)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 73 more
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.6.3

### Scala version/s

2.13.14
