### ISSUE TITLE
Packages not being resolved after upgrading Scala Version

### ISSUE THREAD

**Issue by seansabour** [scalameta/metals#2130]
**Describe the bug**

After upgrading my scalaVersion from 2.12.8 to 2.12.12 I'm getting a ton of dependency resolution errors in my code:
```
object cluster is not a member of akka bloop
object inject is not a member of package com.google bloop
```

my build.sbt
```

lazy val root = project.in(file(".")).settings(
  name := "project",
  scalaVersion := "2.12.12",
  credentials += Credentials(Path.userHome / ".sbt_credentials"),
  logBuffered in Test := false,
).enablePlugins(MultiJvmPlugin, PlayScala, DockerPlugin, JavaAgent).configs(MultiJvm).settings(DockerBuild.settings)

```

Dependencies 
```
import sbt._
import play.sbt.PlayImport._

object Dependencies {
  private final val akkaVersion = "2.6.9"

  def libraries = Seq(
    evolutions,
    ehcache,
    ws,
    specs2                    % Test,
    guice,
    "com.unboundid"          %% "unboundid-ldapsdk"          % "4.0.7",
    "mysql"                  %% "mysql-connector-java"       % "5.1.44",
    "org.scalatestplus.play" %% "scalatestplus-play"         % "4.0.0"     % "test",
    "com.typesafe.akka"      %% "akka-actor"                 % akkaVersion,
    "com.typesafe.akka"      %% "akka-cluster"               % akkaVersion,
    "com.typesafe.akka"      %% "akka-remote"                % akkaVersion,
    "com.typesafe.akka"      %% "akka-stream"                % akkaVersion,
    "com.typesafe.akka"      %% "akka-distributed-data"      % akkaVersion,
    "com.typesafe.akka"      %% "akka-cluster-tools"         % akkaVersion,
    "com.typesafe.akka"      %% "akka-slf4j"                 % akkaVersion,
    "com.typesafe.akka"      %% "akka-multi-node-testkit"    % akkaVersion,
    "com.typesafe.akka"      %% "akka-serialization-jackson" % akkaVersion,
    "com.typesafe.akka"      %% "akka-testkit"               % akkaVersion % Test,
    "com.typesafe.play"      %% "play-slick"                 % "4.0.0",
    "com.typesafe.play"      %% "play-slick-evolutions"      % "4.0.0",
    "com.softwaremill.sttp"  %% "core"                       % "1.2.0",
    "com.softwaremill.sttp"  %% "json4s"                     % "1.2.0",
    "net.liftweb"            %% "lift-json"                  % "3.3.0",
    "com.splunk"             %% "splunk"                     % "1.6.0.0",
    "org.scalamock"          %% "scalamock"                  % "4.2.0"     % Test,
    "org.scalatest"          %% "scalatest"                  % "3.0.5"     % Test,
    "org.mockito"            %% "mockito-core"               % "2.13.0"    % Test,
    "io.swagger"             %% "swagger-play2"              % "1.7.1",
    "com.h2database"         %% "h2"                         % "1.4.199",
    "com.enragedginger"      %% "akka-quartz-scheduler"      % "1.8.2-akka-2.6.x",
    "io.circe"               %% "circe-core"                 % "0.11.1",
    "io.circe"               %% "circe-generic"              % "0.11.1",
    "io.circe"               %% "circe-generic-extras"       % "0.11.1",
    "io.circe"               %% "circe-parser"               % "0.11.1",
    "software.amazon.awssdk" %% "s3"                         % "2.10.61",
    "software.amazon.awssdk" %% "sts"                        % "2.10.62",
    "org.eclipse.jgit"       %% "org.eclipse.jgit"           % "5.6.0.201912101111-r",
    "io.kamon"               %% "kamon-bundle"               % "2.1.0",
    "io.kamon"               %% "kamon-prometheus"           % "2.1.4"
  )
}

```

I also see that the package is installed here:
```
⚡ ls -al ~/Library/Caches/Coursier/v1/https/artifactory.company.com/artifactory/virtrelease/com/typesafe/akka/akka-cluster_2.12/2.6.4/
total 2328
drwxr-xr-x  17 sean.sabour  staff     544 Oct  9 13:13 .
drwxr-xr-x   3 sean.sabour  staff      96 Oct  9 13:12 ..
-rw-r--r--   1 sean.sabour  staff       0 Oct  9 13:13 .akka-cluster_2.12-2.6.4-sources.jar.checked
-rw-r--r--   1 sean.sabour  staff      32 Mar 13  2020 .akka-cluster_2.12-2.6.4-sources.jar__md5
-rw-r--r--   1 sean.sabour  staff      40 Mar 13  2020 .akka-cluster_2.12-2.6.4-sources.jar__sha1
-rw-r--r--   1 sean.sabour  staff      64 Mar 13  2020 .akka-cluster_2.12-2.6.4-sources.jar__sha256
-rw-r--r--   1 sean.sabour  staff       0 Oct  9 13:13 .akka-cluster_2.12-2.6.4.jar.checked
-rw-r--r--   1 sean.sabour  staff      32 Mar 13  2020 .akka-cluster_2.12-2.6.4.jar__md5
-rw-r--r--   1 sean.sabour  staff      40 Mar 13  2020 .akka-cluster_2.12-2.6.4.jar__sha1
-rw-r--r--   1 sean.sabour  staff      64 Mar 13  2020 .akka-cluster_2.12-2.6.4.jar__sha256
-rw-r--r--   1 sean.sabour  staff       0 Oct  9 13:12 .akka-cluster_2.12-2.6.4.pom.checked
-rw-r--r--   1 sean.sabour  staff      32 Mar 13  2020 .akka-cluster_2.12-2.6.4.pom__md5
-rw-r--r--   1 sean.sabour  staff      40 Mar 13  2020 .akka-cluster_2.12-2.6.4.pom__sha1
-rw-r--r--   1 sean.sabour  staff      64 Mar 13  2020 .akka-cluster_2.12-2.6.4.pom__sha256
-rw-r--r--   1 sean.sabour  staff  155488 Mar 13  2020 akka-cluster_2.12-2.6.4-sources.jar
-rw-r--r--   1 sean.sabour  staff  993624 Mar 13  2020 akka-cluster_2.12-2.6.4.jar
-rw-r--r--   1 sean.sabour  staff    3349 Mar 13  2020 akka-cluster_2.12-2.6.4.pom
```

**To Reproduce**

1. Update scalaVersion from 2.12.8 to 2.12.12

**Expected behavior**

Project to continue to work
**Screenshots**

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.4

**Additional context**

**Search terms**

**Comment by seansabour** [comment]
i'm going to leave the ticket open, but something really weird was going on with my sbt.. I ended up removing cache, reinstalling sbt (lol), and even restarting computer. Finally got it working lol


for reference:

clear Coursier cache on mac: ```rm -rf ~/Library/Caches/Coursier/v1``
clear ivy2 cache: 
```
rm -rf ~/.ivy2/cache
```

cleaned up global sbt:
```
rm -rf ~/.sbt
```

deleted .bloop, .metals, target/, /project/project, /project/target

**Comment by ckipp01** [comment]
Thanks for reporting @seansabour. After you updated your Scala Version, you should have gotten prompted to re-import your build. Do you remember this happening, and do you remember if it was successful?

**Comment by tgodzik** [comment]
Let's close it for now and reopen if anything like this happens again.
