### ISSUE TITLE
Error when evaluating worksheet with Scala 3.0.0 using Metal 

### ISSUE THREAD

**Issue by GrapixLeGrand** [scalameta/metals#4893]
### Describe the bug

When creating a worksheet in a Scala sbt project using Scala 3.0.0, the evaluation of the worksheet fails with the following.
errors:

I'm using VSCode 1.73.1 with the Metal extension version 0.11.10.

```
test.worksheet.sc:2 (mdoc generated code) 
 type DocumentBuilder is not a member of mdoc.internal.document - did you mean document.DocumentBuilder?
object MdocSession extends _root_.mdoc.internal.document.DocumentBuilder {
```
```
test.worksheet.sc:5 (mdoc generated code) 
 Not found: $doc
    $doc.startSection();
``` 
```
test.worksheet.sc:9 (mdoc generated code) 
 Not found: $doc
    $doc.binder(res0, 0, 0, 0, 16);
```
```
test.worksheet.sc:10 (mdoc generated code) 
 Not found: $doc
    $doc.endStatement();
```
```
test.worksheet.sc:11 (mdoc generated code) 
 Not found: $doc
    $doc.endSection();
```

In order to reproduce:
1. download some programming assignment in Coursera [here](https://moocs.scala-lang.org/~dockermoocs/handouts/scala-3/forcomp.zip) (progfun1/forcomp). 
2. open with VScode
3. using CTRL + P in VSCode select "Metal: Create Worksheet" 
4. inserting `println("hello")` in the worksheet.

The version of Scala in the build.bst is 3.0.0. It is working fine with Scala 3.2.1.

### Expected behavior

Using version 3.2.1 the worksheet evaluates as expected showing "hello". I was expecting the same using 3.0.0.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

11.0.11

### Extra context or search terms

Output of Metal Doctor:

![Screenshot from 2023-01-24 10-11-54](https://user-images.githubusercontent.com/38352876/214252638-2f31854f-8ec1-4e61-9407-1ae6b2877e95.png)

**Comment by tgodzik** [comment]
Thanks for reporting! Unfortunately, mdoc is currently release with Scala 3.1.x which means that we will be unable to support Scala 3.0.0. We could potentially fallback to an older version of mdoc that supports it, but I'd rather not encourage user to stay with 3.0.x. I hope it's ok if you update to later Scala version?

**Comment by julienrf** [comment]
We are going to update all our assignments and graders to 3.1.x, but in general I think it is important to support Scala versions for as long as possible. What was the reason for requiring 3.1.x?

**Comment by ckipp01** [comment]
> What was the reason for requiring 3.1.x?

In this specific scenario it's mdoc. We published mdoc on 3.1.x meaning that if a user is using 3.0.x in a worksheet, which relies on mdoc, it won't work.

**Comment by julienrf** [comment]
Yes, but I meant what was the reason for requiring 3.1 in mdoc?

**Comment by tgodzik** [comment]
> Yes, but I meant what was the reason for requiring 3.1 in mdoc?

I think I might have worked around the issue, but I would rather avoid downgrading the version. I will do a small workaround for now.
