### ISSUE TITLE
Best effort compilation gives false errors

### ISSUE THREAD

**Issue by brndt** [scalameta/metals#6628]
### Describe the bug

If I make any changes in the code and broke compilation, the compiler now gives me random totally non-related errors.

For example:

https://github.com/user-attachments/assets/a97e9600-d932-47af-9246-abc70ec797e8

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.3.4

**Comment by tgodzik** [comment]
Thanks for reporting! I wonder if this might be connected to the fact that we now compile all modules and sometimes this might lead to worse errors in the dependent modules.

Best effort itself will not produce any new diagnostics.

**Comment by filipwiech** [comment]
I can confirm the same behaviour in my project. :+1: 

Scala 3.5.0-RC6, Bloop 1.6.0, SBT 1.10.1, Metals 1.3.4+23-c744a47f-SNAPSHOT

**Comment by filipwiech** [comment]
One more update (sorry for a lot of messages, but I hope it will be useful info for you): while usually SBT build gives expected results (either a successful compilation or an error that is real and makes sense), I have regularly observed that after a while SBT seems to deteriorate as well and starts spewing weird messages (cannot find imports/types, broken build). After a clean build it starts working again. :slightly_frowning_face:

**Comment by tgodzik** [comment]
We might have to add a setting for that if it turns out to be the problem, but I can't imagine why would this happen.

I will check it out today.

**Comment by tgodzik** [comment]
I will have to disable it, thanks for catching this before the actual release of 3.5.0! I will have to do a new release with this probably tomorrow.

@jchyb is on vacation till 16th, and I think I will have to ask him to take a look again. @brndt is it ok if I share your codebase with him once he's available?

**Comment by brndt** [comment]
> I will have to disable it, thanks for catching this before the actual release of 3.5.0! I will have to do a new release with this probably tomorrow.
> 
> @jchyb is on vacation till 16th, and I think I will have to ask him to take a look again. @brndt is it ok if I share your codebase with him once he's available?

Yes of course.
However I will need to rollback the version to 3.4.2 in main branch, but I will create a separate branch for you with 3.5.0-RC Scala version.

**Comment by gchudnov** [comment]
wondering if there is any update?

with the release of 3.5 tried to enable best effort compiling on `Metals version: 1.3.5+68-5948c4fe-SNAPSHOT` by enabling `-Dmetals.enable-best-effort=true`, but looks like bumped into a similar issue, so disabled it...

**Comment by jchyb** [comment]
Still working on this. It looks like the issue is moreso on the build server side, so the best effort compilation should still work on 3.5 once we fix this issue.

**Comment by filipwiech** [comment]
@jchyb Thank you for looking into this. :+1: Just in case, a related issue #6627 caused by the Best Effort compilation was closed earlier, but that one seems to be somewhat distinct, as it impacts macros specifically, even in a completely clean project build with no other errors. I have no idea if the root cause is the same, but wanted to highlight it, as it might have got lost in the meantime. :slightly_smiling_face:

**Comment by bloznelis** [comment]
Can confirm that this issue persists in **metals 1.3.5** with **Scala 3.5.0** when enabling best effort compilation with `-Dmetals.enable-best-effort=true`.

From what I gathered, there's only one type of error—"value **foo** is not a member of **bar**"—and is triggered only for the imports. Hope this helps to track it down.

**Comment by tgodzik** [comment]
One issue still existing (not sure if caused by best effort) :
- changing a name of a class isn't picked up in downstream projects

**Comment by bloznelis** [comment]
To be honest, I cannot reproduce this issue anymore with:
* Metals 1.4.0
* Scala 3.5.2
* Bloop 2.0.3

**Comment by brndt** [comment]
Copy paste from discord canal:

I've tried to use best effort compilation with the latest version of Bloop and it's unusable :( - having a lot of random and out of sync errors. For example, removing class that's used by the others is no longer detected by the compiler, a vice-versa, like you can see on the screenshot.

<img width="1093" alt="Screenshot_2024-11-21_at_15 59 14" src="https://github.com/user-attachments/assets/5d1c272a-e8fb-4196-914d-53d9a2c6a2f8">

and here it can't even detect 'succeed' method of ZIO

<img width="877" alt="Screenshot_2024-11-21_at_16 03 30" src="https://github.com/user-attachments/assets/cdcd5d51-0f73-4c7c-b2a1-dec3d99b70bb">

**Comment by brndt** [comment]
When using the latest Bloop version I'm getting quite a lot of random falsy errors like this one:

https://github.com/user-attachments/assets/7800118a-d987-4ebb-8ea0-53858d91c9b1

**Comment by tgodzik** [comment]
just to be sure, that's still with best effort?

**Comment by jchyb** [comment]
Also, it would help me to know if any of the vscode auto save options are turned on (for easier reproduction on my end), and if so, whether manual saves after the noticing the issue help
<img width="653" alt="Zrzut ekranu 2024-12-14 o 21 04 42" src="https://github.com/user-attachments/assets/66a0c6e0-c4fe-4a68-bd65-b773aaa16235" />

**Comment by brndt** [comment]
> just to be sure, that's still with best effort?

Yes!

> Also, it would help me to know if any of the vscode auto save options are turned on (for easier reproduction on my end), and if so, whether manual saves after the noticing the issue help 

Yes, I'm using an auto save. I'll try to disable it and see if it helps.

**Comment by jchyb** [comment]
> > Also, it would help me to know if any of the vscode auto save options are turned on (for easier reproduction on my end), and if so, whether manual saves after the noticing the issue help
> 
> Yes, I'm using an auto save. I'll try to disable it and see if it helps.

Thank you! Of course it should still work with auto save, I'll try to look into this and see if I can pinpoint the issue

**Comment by brndt** [comment]
I can confirm it happens without auto save too.
Also I have a bunch of 'falsy' errors I mentioned [here](https://github.com/scalameta/metals/issues/6627)

**Comment by brndt** [comment]
After update to the latest Metals version I still experience the same problems as mentioned here:
https://github.com/scalameta/metals/issues/6627
