### PR TITLE
Trigger didFocus when current compile may affect focused buffer.

### LINKED ISSUE #497: Missing didFocus compile in multi-project build
**To Reproduce**
  
```scala
/p1/src/main/scala/A.scala
class A {
  val foo: Int = 1
}
```

```scala
/p2/src/main/scala/B.scala
class B extends A {
  override val foo: Int = 2
}
```
  
where `p2` depends on `p1`.
  
1. Introduce compilation error in `A` by writing `val foo: Int = String`.
1. Ignore the previous error and introduce another compilation error in B `override val foo: Int = ""`
1. Compile from `B`, Metals will compile `p1` and show an error. Fix it.
1. Come back to `B`, Metals does not trigger compilation and thus the compilation error in `override val foo` is not present.

**Expected behavior**

Metals compiles `p2` and shows me the error.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: latest snapshot

**Additional context**

I suspect this problem has been introduced by https://github.com/scalameta/metals/pull/488 which doesn't take into account the status of the compile requests to deduplicate compile requests.

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #497. Previously, we did not trigger didFocus compiles if there
was an ongoing compilation that might affect the focused buffer. This
could results in missing compilation when fixing an error in main and
then instantly focus on a file in tests before the main compilation
finished.

### CODE REVIEW

**Comment by olafurpg** [comment]
Travis is flaky, ignoring.
