### ISSUE TITLE
Go-to-definition for implicit apply only goes to `apply`

### ISSUE THREAD

**Issue by harpocrates** [scalameta/metals#7267]
### Describe the bug

Code:

```
trait Foo {
  def someNum
  def apply(i: Int): Unit = println(someNum)
}
object Bar extends Foo {
  def someNum = 42
}

object Test {
  Bar(2)
}
```

Cursor on `Bar` in `Bar(2)`, go-to-definition goes to `Foo.apply`.

### Expected behavior

Go-to definition should report _two_ definitions:

  * `object Bar`
  * `def apply` on `Foo`

LSP is designed to accommodate multiple definitions.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

1.5.1

**Comment by harpocrates** [comment]
Looks like this used to work but regressed with https://github.com/scalameta/metals/pull/7028. The semantic DB path handles this, but not the PC one.

What is the thinking around keeping all of the various alternate codepaths? Should this sort of logic now be reimplemented using the PC?

**Comment by kasiaMarek** [comment]
> What is the thinking around keeping all of the various alternate codepaths?

The idea is that in some conditions some of this strategies may fail, so we have multiple fallbacks. The one that should give the most accurate and up to date solution is used as the first one.

> Should this sort of logic now be reimplemented using the PC?

Yeah, ideally behaviour of using `semanticdb` or `pc` in compiling code should be the same.

**Comment by harpocrates** [comment]
Ok, makes sense. I see you def assigned, but let me know if there's anything I can do to help here. I mostly didn't want to go blindly added a parallel code path, but maybe that is what we want in this case.

Long term, sounds like we want at least the preferred strategy to support all features, then the fallbacks can be less expressive.
