### ISSUE TITLE
Worksheets not working in Scala 3.4.0

### ISSUE THREAD

**Issue by spamegg1** [scalameta/metals#6192]
### Describe the bug

@rochala was able to reproduce this locally.

1. Open blank Scala-cli project in VS Code with `project.scala`:
```scala
//> using scala 3.4.0
```
2. Create blank worksheet, type `2+3` and save
3. See error: no evaluation occurs.
![Screenshot from 2024-03-03 11-20-58](https://github.com/scalameta/metals/assets/4255997/eaa8bf39-c1f8-4a9a-8684-7afa8be807ab)

Possibly relevant errors in `metals.log`:
```scala
2024.03.02 23:00:29 ERROR worksheet: /home/spam/Projects/test/test.worksheet.sc
java.lang.NoClassDefFoundError: Could not initialize class dotty.tools.dotc.NoCompilationUnit$
	at dotty.tools.dotc.core.Contexts$FreshContext$.initial(Contexts.scala:749)
	at dotty.tools.dotc.core.Contexts$ContextBase.<init>(Contexts.scala:868)
	at dotty.tools.dotc.Driver.initCtx(Driver.scala:61)
	at mdoc.internal.markdown.MarkdownDriver.<init>(MarkdownCompiler.scala:56)
	at mdoc.internal.markdown.MarkdownCompiler.newContext(MarkdownCompiler.scala:87)
	at mdoc.internal.markdown.MarkdownCompiler.<init>(MarkdownCompiler.scala:99)
	at mdoc.internal.markdown.MarkdownBuilder$.fromClasspath(MarkdownBuilder.scala:99)
	at mdoc.internal.cli.Context$.fromOptions(Context.scala:90)
	at mdoc.internal.worksheets.Mdoc.context(Mdoc.scala:68)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:54)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:361)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:262)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:262)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: xsbti/UseScope [in thread "Evaluating Worksheet test.worksheet.sc"]
	at dotty.tools.dotc.CompilationUnit.<init>(CompilationUnit.scala:85)
	at dotty.tools.dotc.NoCompilationUnit$.<init>(CompilationUnit.scala:116)
	at dotty.tools.dotc.NoCompilationUnit$.<clinit>(CompilationUnit.scala:116)
	at dotty.tools.dotc.core.Contexts$FreshContext$.initial(Contexts.scala:749)
	at dotty.tools.dotc.core.Contexts$ContextBase.<init>(Contexts.scala:868)
	at dotty.tools.dotc.Driver.initCtx(Driver.scala:61)
	at mdoc.internal.markdown.MarkdownDriver.<init>(MarkdownCompiler.scala:56)
	at mdoc.internal.markdown.MarkdownCompiler.newContext(MarkdownCompiler.scala:87)
	at mdoc.internal.markdown.MarkdownCompiler.<init>(MarkdownCompiler.scala:99)
	at mdoc.internal.markdown.MarkdownBuilder$.fromClasspath(MarkdownBuilder.scala:99)
	at mdoc.internal.cli.Context$.fromOptions(Context.scala:90)
	at mdoc.internal.worksheets.Mdoc.context(Mdoc.scala:68)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:54)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:361)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.liftedTree1$1(WorksheetProvider.scala:262)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:262)

2024.03.02 23:00:29 INFO  time: evaluated worksheet 'test.worksheet.sc' in 3ms
```

### Expected behavior

Worksheet should evaluate top-level expression.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

1.2.2+57-f1608f84-SNAPSHOT

### Extra context or search terms

worksheet scala 3.4
