### ISSUE TITLE
Metals will not connect to sbt if compilation fails

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#2347]
**Describe the bug**

If we try to connect to the sbt BSP server on a project that has a compile error, it will not succeed

**To Reproduce**

1. Create a new project
2. Introduce an error
3. Try to switch to sbt bsp

**Expected behavior**

sbt just reports the error.

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.9.8

**Additional context**

This was raised on gitter

**Search terms**

sbt BSP compile error

**Comment by ckipp01** [comment]
Thanks for reporting this @tgodzik! Although I'm unable to reproduce it. This is what I did to test it.

- Create a new sbt project (has sbt 1.4.6)
- Imported with Bloop, went to `Main.scala` and added a `val hi: String = 3`.
- Executed a `metals.generate-bsp-config` which created the `.bsp/sbt.json` and then attempted to connect.

It did connect correctly, and in the logs I see this:

```
2021.01.04 16:50:17 INFO  Attempting to connect to the build server...
2021.01.04 16:50:17 INFO  tracing is enabled: /Users/ckipp/Library/Caches/org.scalameta.metals/bsp.trace.json
2021.01.04 16:50:23 INFO  time: connected to build server in 6.03s
2021.01.04 16:50:23 INFO  Connected to Build server v1.4.6
2021.01.04 16:50:23 INFO  Processing
2021.01.04 16:50:23 INFO  Processing
2021.01.04 16:50:23 INFO  Processing
2021.01.04 16:50:23 INFO  Processing
2021.01.04 16:50:23 INFO  Processing
2021.01.04 16:50:23 INFO  Processing
2021.01.04 16:50:23 INFO  Processing
2021.01.04 16:50:24 INFO  time: imported build in 1.43s
2021.01.04 16:50:24 INFO  Processing
2021.01.04 16:50:24 INFO  time: indexed workspace in 0.6s
2021.01.04 16:50:25 WARN  no build target for: /Users/ckipp/Documents/scala-workspace/tester/build.sbt
2021.01.04 16:50:24 INFO  Processing
2021.01.04 16:50:24 INFO  compiling root
2021.01.04 16:50:24 INFO  compiling 2 Scala sources to /Users/ckipp/Documents/scala-workspace/tester/target/scala-2.13/classes ...
2021.01.04 16:50:25 INFO  Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.4. Compiling...
2021.01.04 16:50:32 INFO    Compilation completed in 6.949s.
2021.01.04 16:50:32 ERROR /Users/ckipp/Documents/scala-workspace/tester/src/main/scala/example/Main.scala:13:20: type mismatch;
 found   : Int(3)
 required: String
2021.01.04 16:50:32 ERROR   val hi: String = 3
2021.01.04 16:50:32 ERROR                    ^
2021.01.04 16:50:32 ERROR one error found
2021.01.04 16:50:32 INFO  time: compiled root in 7.69s
2021.01.04 16:50:32 ERROR (Compile / compileIncremental) Compilation failed
```

I'm assuming this isn't what you're seeing?

**Comment by tgodzik** [comment]
It seems I can no longer reproduce it :thinking: I thought I've seen it a number of times, but maybe new sbt version fixed it? Or I was doing something totally wrong. Either way I will close it and we can reopen if I ever encounter it again.

**Comment by asflierl** [comment]
Hi, I was the person who reported this on Gitter. I can (still) reproduce this.

here's what I do:
1. `git clone https://github.com/asflierl/sglicko2.git`
2. `cd sglicko2`
3. `git checkout db0b84787dcbf1bcceb37db3abf44ba2129c78ec`
4. `sbtn compile`  (this will report a compile error)
5. `code .`
6. in VSCode issue "Metals: switch build server" command and switch to SBT
*BOOM* :) 

I got SBT 1.4.6 installed, Metals updated to 0.9.8 and using GraalVM CE 20.3.0 for Java 11.

Anything else I can do to help diagnose this? @tgodzik @ckipp01

**Comment by ckipp01** [comment]
Hey @asflierl I just pulled down your repo and indeed, it does fail for me as well!

```
2021.01.05 16:37:03 ERROR     }x
2021.01.05 16:37:03 ERROR      ^
2021.01.05 16:37:03 ERROR one error found
2021.01.05 16:37:03 ERROR (Compile / compileIncremental) Compilation failed
2021.01.05 16:37:03 INFO  Processing
2021.01.05 16:37:03 INFO  Disconnecting from sbt session...
2021.01.05 16:37:03 INFO  Shut down connection with build server.
2021.01.05 16:37:03 ERROR Failed to connect with build server, no functionality will work.
org.eclipse.lsp4j.jsonrpc.ResponseErrorException:
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
        at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
🤔 I'm not fully sure why in this instance it behaves differently than with a minimal reproduction. I'll have to dive into this a bit more to figure out why it's disconnecting in this scenario and not the other. Thanks for following up!

**Comment by ckipp01** [comment]
I have some good news and I have some bad news.

### Good news
I was able to figure out what's going on here. The issues lies with the `benchmark` project in your repo.

```
val benchmark = project
  .dependsOn(sglicko2)
  .enablePlugins(JmhPlugin)
  .settings(
    fork := true,
    scalacOptions := Seq(
      "-unchecked",
      "-deprecation",
      "-language:_",
      "-encoding",
      "UTF-8",
      "-target:jvm-1.8"
    ),
    javaOptions := Seq(
      "-Dfile.encoding=UTF-8",
      "-Duser.country=US",
      "-Duser.language=en",
      "-Xms4g",
      "-Xmx4g",
      "-Xss1m",
      "-XX:+UseG1GC",
      "-XX:MaxGCPauseMillis=1",
      "-XX:MaxInlineLevel=20"
    ),
    libraryDependencies ++= Seq(
      "org.json4s" %% "json4s-native" % "3.6.10",
      "org.typelevel" %% "spire" % "0.17.0"
    ),
    headerLicense := (ThisBuild / headerLicense).value
  )
```
You'll notice that if you still have a compilation error, comment this module out, and then try a fresh connection to sbt, it will succeed as you'd expect. The real is is that when this project is added, you get a few more build targets:

	* `/sglicko2/#benchmark/Compile`
	* `/sglicko2/#benchmark/Test`
	* `/sglicko2/#benchmark/Jmh`

Once we have those build targets, we send a [Build Target Source Request](https://build-server-protocol.github.io/docs/specification.html#build-target-sources-request), and this is where stuff goes wrong. Mainly, this never returns from sbt, and you're left with:

```
[Trace - 00:11:46 PM] Received response 'buildTarget/sources - (4)' in 758ms
Result: null
Error: {
  "code": -33000,
  "message": ""
}
```
Since this fails, our `importBuild()` fails -> `importBuilds()` fails -> `connectToNewBuildServer()` fails -> and finally `autoConnectToBuildServer()` fails, which causes you to fall into the recover which has a `disconnectOldBuidServer()` call. 

https://github.com/scalameta/metals/blob/d93271973db348ca0bb6ff11dd4e6cbc81d1ffed/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala#L1891-L1924

Now, I think we can clean this up a bit on our side, and I don't actually think the disconnect is even needed there if the `Future` fails, but ultimately the issue lies with the `buildTarget/sources` not being returned. From trying this with Bloop, it seems that they are correctly returned there.

### The Bad news

The bad new is just that I really don't know how to fix this. I think this may actually need to be something we submit upstream to sbt, since `buildTarget/sources` should be returned here. However, I do want to confirm that before pushing this away, especially since I think there might be some things we can do on our end to make this situation at least a bit clearer for the user. @tgodzik do you have any thoughts on this? Or even @adpi2 from the sbt BSP perspective, do you have any ideas?

**Comment by adpi2** [comment]
Thanks @ckipp01 for this detailed diagnosis.

The `buildTarget/sources` is really the same as running:
```
sbt:sglicko2> <project> / <config> / managedSources
sbt:sglicko2> <project> / <config> / unmanagedSources
```

Here the problem must be that, for some `<project> / <config>`, the `managedSources` or the `unmanagedSources` triggers some compilation which in turn fails. And indeed:
```
sbt:sglicko2> benchmark / Jmh / managedSources
[info] compiling 10 Scala sources to /home/piquerez/asflier/sglicko2/target/scala-2.13/classes ...
[error] /home/piquerez/asflier/sglicko2/src/main/scala/sglicko2/Glicko2.scala:61:6: value x is not a member of Double
[error] possible cause: maybe a semicolon is missing before `value x`?
[error]     }x
[error]      ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed Jan 19, 2021, 12:57:27 PM
```

My conclusion is that it's not reliable to import `benchmark / Jmh` as a build target. So we should disable that:
```scala
val benchmark = project
  .dependsOn(sglicko2)
  .enablePlugins(JmhPlugin)
  .settings(
    Jmh / bspEnabled := false,
    ...
  )
```

Then reload and connect works perfectly and we have 3 build targets:
- `benchmark`
- `sglicko2`
- `sglicko2-test`

What can be improved there:
  - Ideally the `Jmh / bspEnabled := false` should be set by the `JmhPlugin` itself.
  - Maybe sbt should be forgiving on `buildTarget/sources` when it fails for one `buildTarget` so that the sources of the other build targets are returned.

**Comment by ckipp01** [comment]
> Ideally the Jmh / bspEnabled := false should be set by the JmhPlugin itself.

If I'm remembering correctly, we've hit on Jmh stuff before causing issues. I'll try to look at Jmh upstream and see if I can maybe fix that since it seems pretty simple.

> Maybe sbt should be forgiving on buildTarget/sources when it fails for one buildTarget so that the sources of the other build targets are returned.

I'll look into a few things here. Thanks for the input @adpi2!
