### PR TITLE
Factor out a ClasspathLoader.getURLs(classLoader) helper for java9+ compatability, update usages

### PR DESCRIPTION
**Pull request by er1c**
This updates https://github.com/scalameta/metals/pull/739, tests still fail on java11, but no longer from  `Caused by: java.lang.NoClassDefFoundError: javax/tools/ToolProvider`

```
sbt:default-40f014> unit/testOnly -- tests.DocumentHighlightSlowSuite.single
[info] Compiling 1 Scala source to /c/Users/Eric Peters/IdeaProjects/metals/metals/target/scala-2.12/classes ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/c/Users/Eric%20Peters/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.8/4.1.9/semanticdb-scalac_2.12.8-4.1.9.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Done compiling.
------------ Running Tests tests.DocumentHighlightSlowSuite.single ------------
------------ Running Tests tests.DocumentHighlightSlowSuite.single ------------
INFO  tests.TestingServer#initialize
INFO  time: generated quick build in 1.3s
INFO  logging to file /c/Users/Eric Peters/IdeaProjects/metals/tests/unit/target/e2e/documentHighlight/single/.metals/metals.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/c/Users/Eric%20Peters/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.8/4.1.9/semanticdb-scalac_2.12.8-4.1.9.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  time: initialize in 0.28s
INFO  running embedded 'bloop bsp --protocol local --socket /tmp/bsp13549952426963183349/-9uxbm22vm0b.socket'
The server is listening for incoming connections at local:///tmp/bsp13549952426963183349/-9uxbm22vm0b.socket...
Accepted incoming BSP client connection at local:///tmp/bsp13549952426963183349/-9uxbm22vm0b.socket
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /c/Users/Eric Peters/.cache/metals/bsp.trace.json
request received: build/initialize
INFO  time: connected to build server in 3.55s
BSP initialization handshake complete.
INFO  time: indexed workspace in 0.53s
WARN  no build target:
INFO  tests.TestingServer#didOpen
INFO  tests.TestingServer#didChange
+ tests.DocumentHighlightSlowSuite.single 8959ms
shutdown request received: build/shutdown
[E] BSP server cancelled, closing socket...
Client in /c/Users/Eric Peters/IdeaProjects/metals/tests/unit/target/e2e/documentHighlight/single/.bloop triggered cancellation. Cancelling tasks...
INFO  bloop exit: 0
Tests: 1, Passed: 1, Failed: 0
[info]
[success] Total time: 20 s, completed Jun 13, 2019, 8:48:10 PM
```

### CODE REVIEW

**Comment by er1c** [comment]
At first glance, the `JdkSources` detection for `src.zip` seems to be correct:

```
scala> scala.meta.internal.metals.JdkSources.getOrThrow
res2: scala.meta.io.AbsolutePath = /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/src.zip
```

Java9: https://docs.oracle.com/javase/9/install/installed-directory-structure-jdk-and-jre.htm: `/jdk-9/src.zip`
Java10: https://docs.oracle.com/javase/10/install/installed-directory-structure-jdk-and-jre.htm: `/jdk-10/src.zip`
Java11: https://docs.oracle.com/en/java/javase/11/install/installed-directory-structure-jdk.html: `/jdk-interim.update.patch.jdk/lib/src.zip`
Java12: https://docs.oracle.com/en/java/javase/12/install/installed-directory-structure-jdk.html: `/jdk-interim.update.patch.jdk/lib/src.zip`

The current code in https://github.com/scalameta/metals/blob/4acd4659473321b897ce4059215656dbce4353d5/mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala seems to correctly detect both patterns.

**Comment by er1c** [comment]
Tracked a little bit more down, this line: https://github.com/scalameta/scalameta/blob/0a7bee1a1e85597f614f86a8a7a80d5641c4d1e0/semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/SymbolIndex.scala#L14

returns true in java8, and false in java11, so the `PackageLookup` never gets returned.

**Comment by er1c** [comment]
Adding includeJdk=true to `GlobalSymbolTable` in `BaseExpectSuite`, drops the failing tests to 11: `Tests: 436, Passed: 425, Failed: 11`

**Comment by olafurpg** [comment]
@er1c I've tracked down the cause of the src.zip errors on JDK 11, the file paths have a `/java.base/` prefix
```scala
tests.DefinitionSuite.testCases:43 path: AbsolutePath(/java.base/java/lang/Object.java)
```
The fix should be simple in our navigation index.

**Comment by olafurpg** [comment]
There are four remaining `unit/test` failures on JDK 11 for my computer
```
Tests: 436, Passed: 432, Failed: 4
```
They seem to be related to the `jrt://` file system, I'm investigating.

**Comment by olafurpg** [comment]
I have the new `jrt://` filesystem working and tests passing but I'm looking into a performance regression while walking the significantly larger JDK 11 boot classpath.

File: tests/unit/src/main/scala/tests/BaseExpectSuite.scala [hunk 1]
```diff
@@ -20,7 +20,8 @@ abstract class BaseExpectSuite(val suiteName: String) extends BaseSuite {
         }
         .getOrElse(Classpath(Nil))
     GlobalSymbolTable(
-      input.classpath ++ bootClasspath
+      input.classpath ++ bootClasspath,
```
Comment (er1c) [inline tests/unit/src/main/scala/tests/BaseExpectSuite.scala]: Note for myself: the `GlobalSymbolTable` uses `ClasspathIndex` under the hood, so manually adding in the bootClasspath isn't needed, as it already is applied by the `includeJdk = true`: https://github.com/scalameta/scalameta/blob/18229e37d89f7982ef65a8b034edb0f503fd63cc/semanticdb/metacp/src/main/scala/scala/meta/internal/classpath/ClasspathIndex.scala#L67-L82

Try deleting the (duplicated) bootClasspath code here and make sure it doesn't affect anything, also saw: https://github.com/scalameta/metals/pull/767/files which seemed to strip it out without any undesirable side effects.
