### ISSUE TITLE
Missing didFocus compile in multi-project build

### ISSUE THREAD

**Issue by jvican** [scalameta/metals#497]
**To Reproduce**
  
```scala
/p1/src/main/scala/A.scala
class A {
  val foo: Int = 1
}
```

```scala
/p2/src/main/scala/B.scala
class B extends A {
  override val foo: Int = 2
}
```
  
where `p2` depends on `p1`.
  
1. Introduce compilation error in `A` by writing `val foo: Int = String`.
1. Ignore the previous error and introduce another compilation error in B `override val foo: Int = ""`
1. Compile from `B`, Metals will compile `p1` and show an error. Fix it.
1. Come back to `B`, Metals does not trigger compilation and thus the compilation error in `override val foo` is not present.

**Expected behavior**

Metals compiles `p2` and shows me the error.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: latest snapshot

**Additional context**

I suspect this problem has been introduced by https://github.com/scalameta/metals/pull/488 which doesn't take into account the status of the compile requests to deduplicate compile requests.

**Comment by jvican** [comment]
Nice, thank you for fixing.
