### ISSUE TITLE
Metals seems to recompile everything, very slow highlighting 

### ISSUE THREAD

**Issue by Hakimba** [scalameta/metals#5334]
### Describe the bug

Hi, i just download vscode § installed metals and scala syntax plugins, i have sbt too (script version : 1.8.3, version on the project : 1.7.1) and i use scala 2.13.10.

I can't say much more unfortunately (company stuff etc), i just have the big problem that whevener i change a thing in a source file, metals seems to recompile the entire project because it takes like 1/2min for me to see the changes in the highlighting errors

Metals is on bloop by default, i tried sbt but its worse, metals just loop endlessly on compiling the project and being blocked on 0%

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0;5;6

**Comment by tgodzik** [comment]
Thanks for reporting! Unfortunately without any details it's hard to debug what is going on. Does the sbt work properly if run from CLI? Do you see anything in the logs or `.metals/metals.log`?

**Comment by tgodzik** [comment]
One option here would be to check Bloop with verbose logging via CLI `bloop compile --verbose <module_name>` which should show why it's recompiling everything.

**Comment by Hakimba** [comment]
> Thanks for reporting! Unfortunately without any details it's hard to debug what is going on. Does the sbt work properly if run from CLI? Do you see anything in the logs or `.metals/metals.log`?

Yes sbt works well in CLI, its only a matter of metals and vscode, i can't give much detail about the project itself, the only thing i know is that every time i change a thing in the code, i see the bottom right bar that the project is recompiled, so the feedbacks/features of metals are very slow.

Oh and i have many compilation errors in my case, i don't know if its faster without errors.

My metals.log (i removed some details about the paths etc) is like : 

```
2023.06.14 09:57:55 INFO  Started: Metals version 0.11.12 in workspace ... for client Visual Studio Code 1.79.1.
Jun 14, 2023 9:57:55 AM org.flywaydb.core.internal.license.VersionPrinter printVersionOnly
INFO: Flyway Community Edition 9.16.3 by Redgate
Jun 14, 2023 9:57:55 AM org.flywaydb.core.internal.license.VersionPrinter printVersion
Jun 14, 2023 9:57:55 AM org.flywaydb.core.internal.license.VersionPrinter printVersion
INFO: 
Jun 14, 2023 9:57:56 AM org.flywaydb.core.internal.database.base.BaseDatabaseType createDatabase
INFO: Database: jdbc:h2:file:/......./.metals/metals (H2 2.1)
Jun 14, 2023 9:57:56 AM org.flywaydb.core.internal.command.DbValidate validate
INFO: Successfully validated 4 migrations (execution time 00:00.063s)
Jun 14, 2023 9:57:56 AM org.flywaydb.core.internal.command.DbMigrate migrateGroup
INFO: Current version of schema "PUBLIC": 4
Jun 14, 2023 9:57:56 AM org.flywaydb.core.internal.command.DbMigrate logSummary
INFO: Schema "PUBLIC" is up to date. No migration necessary.
2023.06.14 09:57:57 INFO  time: initialize in 1.46s
2023.06.14 09:58:00 INFO  Attempting to connect to the build server...
2023.06.14 09:58:00 INFO  Running BSP server List(/.....sdkman/candidates/java/22.3.r17-grl/bin/java, -Xms100m, -Xmx100m, -classpath, /..../.sdkman/candidates/sbt/1.8.3/bin/sbt-launch.jar, -Dsbt.script=/..../.sdkman/candidates/sbt/current/bin/sbt, xsbt.boot.Boot, -bsp)
2023.06.14 09:58:00 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /..../.metals/bsp.trace.json or /......cache/metals/bsp.trace.json
2023.06.14 09:58:01 WARN  No build session currently active to reload.
2023.06.14 09:58:05 INFO  time: Connected to build server in 4.51s
2023.06.14 09:58:05 INFO  Connected to Build server: sbt v1.7.1
2023.06.14 09:58:05 INFO  Processing workspace/buildTargets
2023.06.14 09:58:05 INFO  Processing buildTarget/scalacOptions
2023.06.14 09:58:07 INFO  Processing buildTarget/sources
2023.06.14 09:58:07 INFO  Processing buildTarget/dependencySources
2023.06.14 09:58:08 INFO  time: Imported build in 2.66s
2023.06.14 09:58:45 INFO  time: indexed workspace in 37s
2023.06.14 09:58:45 INFO  Processing buildTarget/scalaMainClasses
2023.06.14 09:58:45 INFO  compiling some-driver
2023.06.14 09:58:54 INFO  time: compiled some-driverin 7.86s
2023.06.14 09:58:54 INFO  compiling other-driver
2023.06.14 09:58:54 INFO  compiling project
2023.06.14 09:58:54 INFO  compiling ....
2023.06.14 09:58:54 INFO  compiling 19 Scala sources to ...
2023.06.14 09:58:54 INFO  time: compiled other-other-driver in 10ms
2023.06.14 09:58:54 INFO  compiling 541 Scala sources and 4 Java sources to ....


```

after that i have all the compilation errors, and i have this again, **every time** i change a thing in a source file
```
 2023.06.14 10:03:28 INFO  time: compiled rafale in 4m33s
2023.06.14 10:03:28 INFO  Processing buildTarget/scalaTestClasses
2023.06.14 10:03:28 INFO  compiling driver
2023.06.14 10:03:28 INFO  time: compiled driver in 1ms
2023.06.14 10:03:28 INFO  compiling other driver
2023.06.14 10:03:28 INFO  compiling the project
2023.06.14 10:03:28 INFO  compiling other-other-driver
2023.06.14 10:03:28 INFO  compiling 19 Scala sources to /...../rafal/ckh-driver/target/scala-2.13/it-classes ...
2023.06.14 10:03:28 INFO  time: compiled some driver in 6ms
2023.06.14 10:03:28 INFO  compiling 541 Scala sources and 4 Java sources to /...../rafal/target/scala-2.13/classes ...
```
so it basically recompile the 541 sources everytime. Sorry i'm very very bad at writing a good issue, tell me what kind of info do you need and i'll try my best to give them.

**Comment by Hakimba** [comment]
Other detail : i didn't install bloop myself, i just use vscode which seems to take care of everything regarding bloop (it tells me that it succeed to connect to a bloop server so...)

**Comment by ckipp01** [comment]
> Metals is on bloop by default, i tried sbt but its worse, metals just loop endlessly on compiling the project and being blocked on 0%

When using sbt as your build server are you able to provide any more logs just to try and get a better idea of what is happening?

**Comment by yohannj** [comment]
Hi,
Stumbled on this issue as I was having the same problem.

In my situation, my host is Windows 11, and my project is located inside a Debian VM, on a path that is shared between Windows and Debian.
In that situation, sbt's incremental compilation seemed to work much better than bloop's, but was still slow.

I'm pretty sure Windows is messing up with cache files somehow, leading incremental compilation to think it has to recompile most of the project every time.

Solution: I kept the project inside the VM but moved it on a path that is not shared with Windows, and it now works like a charm.

**Comment by ColOfAbRiX** [comment]
Same here, recompilation is always very slow, with 100% cpu usage and it causes a lot of pain every time I save something, for a couple of minutes each time

**Comment by tgodzik** [comment]
Usually this was caused by some kind of loop with generated sources, but you can take a closer look why things are invalidated by setting the compilation to verbose in metals settings

**Comment by tgodzik** [comment]
There is a verboseCompilation option, but it seems I broke it a while ago :/ 

Fixing it now https://github.com/scalameta/metals/pull/7571

**Comment by harpocrates** [comment]
I don't think there was any crash, but I'll double check. Verbose compilation flag is definitely what I was looking for.

Will that send the verbose-level Bloop logs to the Metals output channel or should I expect to have to go to the central Bloop daemon logs?
